sudo: false
language: node_js
node_js:
- 'stable'
branches:
only:
- master
cache:
directories:
- node_modules
- ~/.npm
- .jest
before_install:
- npm update
install:
- npm install
- npm install react-native-animatable --save npm install
script:
- npm test

# - npm run coveralls
